---
title: "Live Session Assignment 6"
author: "Chris Irwin"
date: "10/15/2016"
output: html_document
---

Please load the following packages (plyr, gdata)
```{r include=FALSE}
library(plyr)
library(gdata)
library(plotly)
library(sqldf)
```

```{r}
qns <- read.csv("rollingsales_Queens.csv",skip=4,header=TRUE)
qns$SALE.PRICE.N <- as.numeric(gsub("[^[:digit:]]","", qns$SALE.PRICE))
names(qns) <- tolower(names(qns))
qns$gross.sqft <- as.numeric(gsub("[^[:digit:]]","", qns$gross.square.feet))
qns$land.sqft <- as.numeric(gsub("[^[:digit:]]","", qns$land.square.feet))
qns$year.built <- as.numeric(as.character(qns$year.built))
qns.sale <- qns[qns$sale.price.n!=0,]
qns.homes <- qns.sale[which(grepl("FAMILY",qns.sale$building.class.category)),]

```

Create a plot to show Gross SQ Ft vs Sales Price  
```{r}
plot(qns.sale$gross.sqft,qns.sale$sale.price.n)
```

Due to the extreme outliers we can try a log transformation 
```{r}
plot(log10(qns.sale$gross.sqft),log10(qns.sale$sale.price.n))
```

Now we want to look at 1, 2 and 3 family homes
```{r}
plot(log10(qns.homes$gross.sqft),log10(qns.homes$sale.price.n))
```


Remove Outliers from data set
```{r}
qns.homes$outliers <- (log10(qns.homes$sale.price.n) <=5) + 0
qns.homes <- qns.homes[which(qns.homes$outliers==0),]
plot(log(qns.homes$gross.sqft),log(qns.homes$sale.price.n))
```



Median House Prices Per Neighborhood
```{r}

average.PricePerHood <- sqldf('select neighborhood, avg([sale.price.n]) as AverageOfHood from [qns.homes] group by neighborhood order by neighborhood')

 plot_ly(x = average.PricePerHood$neighborhood, y= average.PricePerHood$AverageOfHood, Name = "Average Price per Neighborhood", type = "bar")
```








